version: "3.7"

services:

  flask:
    build: ./env
    container_name: flask
    restart: always
    environment:
      - APP_NAME=FlaskCrmUygulamasi
    expose:
      - 5000

  nginx:
    build: ./sunucu
    container_name: nginx
    restart: always
    ports:
      - "80:80"